### ISSUE TITLE
有计划支持ant-design-vue吗

### ISSUE THREAD

**Issue by plus1998** [wingsico/vite-babel-plugin#2]
elementPlus很好用啊，感谢作者付出
有没有计划支持
babel-plugin-import
ant-design-vue

**Comment by wzono** [comment]
> elementPlus很好用啊，感谢作者付出
> 有没有计划支持
> babel-plugin-import
> ant-design-vue

很高兴能帮上一点忙，该仓库目前只是测试版本，会在以后进行完善。

如果有帮助，不妨点个star，谢谢~
