### ISSUE TITLE
Plugin type mismatch

### ISSUE THREAD

**Issue by krry** [wingsico/vite-babel-plugin#4]
Using this with Vite 2 and Typescript, the Plugin type throws an error.

```
Type '{ rollupInputOptions: { plugins: Plugin[]; }; }' is not assignable to type 'Plugin | Plugin[]'.
  Type '{ rollupInputOptions: { plugins: Plugin[]; }; }' is missing the following properties from type 'Plugin[]': length, pop, push, concat, and 26 more.ts(2322)
```

I'm not sure how to resolve this. Do you have any advice?

**Comment by wzono** [comment]
> Using this with Vite 2 and Typescript, the Plugin type throws an error.
> 
> ```
> Type '{ rollupInputOptions: { plugins: Plugin[]; }; }' is not assignable to type 'Plugin | Plugin[]'.
>   Type '{ rollupInputOptions: { plugins: Plugin[]; }; }' is missing the following properties from type 'Plugin[]': length, pop, push, concat, and 26 more.ts(2322)
> ```
> 
> I'm not sure how to resolve this. Do you have any advice?

I'm sorry for that, now development of this repo has been suspended. And it does not support vite 2, may be you can try other plugin. Thank you for your issue.
